version: '3'

services:
  facile-challenge-app:
    container_name: facile-challenge-api
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3333:3333
    networks:
      - facile-network
    depends_on:
      - "facile-challenge-db"


  facile-challenge-db:
    image: postgres:alpine
    container_name: facile-challenge-db
    restart: always
    env_file:
      - .env
    ports:
      - 5342:5342
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - facile-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 3535:8080
    networks:
      - facile-network

networks:
  facile-network:
    driver: bridge
